import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

import { FolderCog, Loader2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

import { useEffect, useState } from "react";

import usePost from "@/hooks/usePost";
import usePut from "@/hooks/usePut";

import { ScrollArea } from "@/components/ui/scroll-area";

import { setIsWarehouseDialogOpen, useWarehousesStore } from "../store";
import { warehouseSchema } from "@/utils/validation/warehouse";



import { toast } from "sonner";

import { WAREHOUSES_URL } from "@/utils/constants/urls";


import { customFormatDate, generateFormattedCode } from "@/utils/methods";
import { useTranslation } from "react-i18next";
import { MapContainer, TileLayer, Marker, useMapEvents } from "react-leaflet";

import L from "leaflet";
import "leaflet/dist/leaflet.css";
delete (L.Icon.Default.prototype)._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: "https://unpkg.com/leaflet@1.9.3/dist/images/marker-icon-2x.png",
  iconUrl: "https://unpkg.com/leaflet@1.9.3/dist/images/marker-icon.png",
  shadowUrl: "https://unpkg.com/leaflet@1.9.3/dist/images/marker-shadow.png",
});

const defaultFormFields = {
  code: "",
  name: "",
  // redeemed_at: customFormatDate(new Date()),
  latitude:"",
  longitude:""
};

export default function WarehouseDialog() {
  const { isWarehouseDialogOpen, selectedWarehouse } = useWarehousesStore();

  const [formFields, setFormFields] = useState(defaultFormFields);


  const form = useForm({
    resolver: yupResolver(warehouseSchema),
    defaultValues: defaultFormFields,
  });

  const [isSubmit, setIsSubmit] = useState(false);
  const {t} = useTranslation()

  const onFinish = () => {
    setFormFields(defaultFormFields);
    form.reset();
    setIsWarehouseDialogOpen(false);
  };
  const {
    mutate: postMutate,

    isPending: isPostAction,
  } = usePost({
    queryKey: "warehouses",
    onSuccess: onFinish,
  });
  const {
    mutate: putMutate,

    isPending: isPutAction,
  } = usePut({
    queryKey: "warehouses",
    onSuccess: onFinish,
  });

  useEffect(() => {
    if (
      formFields.code &&
    
      formFields.name
    ) {
      setIsSubmit(true);
    } else {
      setIsSubmit(false);
    }
  }, [formFields,]);

  useEffect(() => {
    if (selectedWarehouse?.id && isWarehouseDialogOpen) {
      setFormFields({
        code: selectedWarehouse?.code,
        name: selectedWarehouse?.name,
        latitude: selectedWarehouse?.latitude || "",
        longitude: selectedWarehouse?.longitude || "",
        // redeemed_at: selectedWarehouse.redeemed_at,
       
      });

      form.setValue("code", selectedWarehouse?.code);
      form.setValue("name", selectedWarehouse?.name);
      form.setValue("latitude", selectedWarehouse?.latitude);
      form.setValue("longitude", selectedWarehouse?.longitude);

      // form.setValue("redeemed_at", selectedWarehouse?.redeemed_at);
    
    } else {
      // this is server error or other error that could happen
      setFormFields(defaultFormFields);

      form.reset();
    }
  }, [selectedWarehouse]);



  const AutoGeneratedCode = () => {
        const code=generateFormattedCode()
        setFormFields({
          ...formFields,
        code: code,
       
       
      });
      form.setValue("code", code);
  };

  function LocationSelector({ form, fieldLat, fieldLng }) {
    const lat = form.watch(fieldLat);
    const lng = form.watch(fieldLng);
    const position = lat && lng ? [parseFloat(lat), parseFloat(lng)] : null;

    useMapEvents({
      click(e) {
        const { lat, lng } = e.latlng;
        form.setValue(fieldLat, lat.toString());
        form.setValue(fieldLng, lng.toString());
      },
    });

    return position ? <Marker position={position} /> : null;
  }


  const onClose = () => {
    setIsWarehouseDialogOpen(false);
    form.reset();
    setFormFields(defaultFormFields);
  };

  useEffect(() => {
    return () => {
      onClose();
    };
  }, []);

  const onSubmit = async () => {
    // Validate currency Change
    if (
      !formFields.code ||
      !formFields.name 
 
    ) {
      return toast("Please fill all the fields");
    }

    // const formData = {
    //   code: formFields.code,
    //   name: formFields.name,
    //   latitude: formFields?.latitude || "",
    //   longitude: formFields?.longitude || ""
    //   // redeemed_at: customFormatDate(formFields.redeemed_at),
    // };

    const values = form.getValues();

    const formData = {
      code: values.code,
      name: values.name,
      latitude: values.latitude
      ? parseFloat(values.latitude).toFixed(6)
      : "",
      longitude: values.longitude
      ? parseFloat(values.longitude).toFixed(6)
      : "",
    };
    

    if (selectedWarehouse?.id) {

      putMutate({
        endpoint: WAREHOUSES_URL,
        id: selectedWarehouse?.id + "/",

        body: formData,
      
      });
    } else {
      postMutate({
        endpoint: WAREHOUSES_URL,
        body: formData,
       
      });
    }
  };

  return (
    <Dialog open={isWarehouseDialogOpen} onOpenChange={setIsWarehouseDialogOpen}>
      <DialogContent className="max-w-[95%] sm:max-w-[80%] md:w-[600px] max-h-[90vh] ">
        <ScrollArea className=" h-fit pr-4 w-full ">
          <DialogHeader className={"mb-4"}>
            <DialogTitle>
              {selectedWarehouse?.id ? t("Edit") : t("Create")} {t("warehouse")}
            </DialogTitle>
            <DialogDescription>
              {selectedWarehouse?.id ? t("Make changes to your Warehouse here.") : 
              t("Create Warehouse here.")} {t("Click save when you are done.")}
            </DialogDescription>
          </DialogHeader>

          <Form {...form} className="h-full bg-black">
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 ">
              <FormField
                control={form.control}
                name="code"
                render={({ field }) => (
                  <FormItem className="w-full px-1 pt-0">
                    <FormLabel>
                      {" "}
                      {t("Code")}
                      <span className="text-red-500 text-lg">*</span>
                    </FormLabel>
                    <FormControl>
                         <div className="relative">

                      <Input
                        type="text"
                        placeholder={t("Enter Code")}
                        value={field.value}
                        onChange={(e) => {
                          field.onChange(e.target.value);

                          setFormFields({
                            ...formFields,
                            code: e.target.value,
                          });
                        }}
                        className="mb-5"
                      />
                       <Button
                              type="button"
                              variant="ghost"
                              size="icon"
                              className="absolute right-0 top-0 h-full px-3 py-1 hover:bg-transparent  hover:text-slate-900 text-slate-700 dark:text-slate-400 "
                              onClick={AutoGeneratedCode}
                            >
                       
                                <FolderCog size="16" aria-hidden="true" />
                              
                              <span className="sr-only">
                               {t("generate code")}
                              </span>
                            </Button>
                         </div>
                    </FormControl>

                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
  control={form.control}
  name="name"
  render={({ field }) => (
    <FormItem className="w-full px-1 pt-0">
      <FormLabel>
        {" "}
        {t("name")}
        <span className="text-red-500 text-lg">*</span>
      </FormLabel>
      <FormControl>
        <Input
          placeholder={t("Enter Name")}
          value={field.value}
          onChange={(e) => {
            field.onChange(e.target.value);

            setFormFields({
              ...formFields,
              name: e.target.value,
            });
          }}
    
          className=""
        />
      </FormControl>

      <FormMessage />
    </FormItem>
  )}
/>
              {/* <FormField
                control={form.control}
                name="latitude"
                render={({ field }) => (
                  <FormItem className="w-full px-1 pt-0">
                    <FormLabel>{t("Latitude")}</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        step="any"
                        min={-90}
                        max={90}
                        placeholder={t("Enter latitude")}
                        value={field.value}
                        onChange={(e) => {
                          field.onChange(e.target.value);
                          setFormFields({
                            ...formFields,
                            latitude: e.target.value,
                          });
                        }}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="longitude"
                render={({ field }) => (
                  <FormItem className="w-full px-1 pt-0">
                    <FormLabel>{t("Longitude")}</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        step="any"
                        min={-180}
                        max={180}
                        placeholder={t("Enter longitude")}
                        value={field.value}
                        onChange={(e) => {
                          field.onChange(e.target.value);
                          setFormFields({
                            ...formFields,
                            longitude: e.target.value,
                          });
                        }}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              /> */}
              <div className="h-[250px] overflow-hidden mt-3 rounded-md">
  <MapContainer
    center={[33.3128, 44.3615]} // Baghdad default
    zoom={6}
    className="h-full overflow-hidden w-full"
  >
    <TileLayer
      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      attribution='&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a>'
    />
    <LocationSelector
      form={form}
      fieldLat="latitude"
      fieldLng="longitude"
    />
  </MapContainer>
</div>


                {/* <FormField
                  control={form.control}
                  name="start_date_at"
                  render={({ field }) => (
                    <FormItem className="w-full px-0 pt-0">
                      <FormLabel>
                        {" "}
                        {t("start_date_at")}
                        <span className="text-red-500 text-lg">*</span>
                      </FormLabel>
                      <FormControl>
                        <DatePicker
                          date={formFields.start_date_at}
                          setDate={(value) => {
                            field.onChange(value);

                            setFormFields({
                              ...formFields,
                              start_date_at: value,
                            });
                          }}
                        />
                      </FormControl>

                      <FormMessage />
                    </FormItem>
                  )}
                /> */}
   


              <div className="flex flex-row rtl:flex-row-reverse justify-start items-center w-full py-2 gap-4">
                <Button
                  disabled={!isSubmit || isPostAction || isPutAction}
                  type="submit"
                >
                  {isPostAction || isPutAction ? (
                    <p className="flex justify-center items-center space-x-2">
                      <Loader2 className=" h-5 w-5 animate-spin" />
                      <span>{t("Please wait")}</span>
                    </p>
                  ) : (
                    <span>{t("Save")}</span>
                  )}
                </Button>
                <Button type="button" variant="secondary" onClick={onClose}>
                  {t("Cancel")}
                </Button>
              </div>
            </form>
          </Form>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
