import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

import { FolderCog, Loader2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

import { useEffect, useState } from "react";

import usePost from "@/hooks/usePost";
import usePut from "@/hooks/usePut";

import { ScrollArea } from "@/components/ui/scroll-area";

import { setIsGiftCardDialogOpen, useGiftCardsStore } from "../store";
import { giftCardSchema } from "@/utils/validation/gift-card";



import { toast } from "sonner";

import { ADMIN_GIFT_CARDS_URL } from "@/utils/constants/urls";


import DatePicker from "@/components/ui/date-picker";
import { customFormatDate, generateFormattedCode } from "@/utils/methods";
import { useTranslation } from "react-i18next";


const defaultFormFields = {
  code: "",
  amount_iqd: "",
  redeemed_at: customFormatDate(new Date()),
};

export default function GiftCardDialog() {
  const { isGiftCardDialogOpen, selectedGiftCard } = useGiftCardsStore();

  const [formFields, setFormFields] = useState(defaultFormFields);


  const form = useForm({
    resolver: yupResolver(giftCardSchema),
    defaultValues: defaultFormFields,
  });

  const [isSubmit, setIsSubmit] = useState(false);
  const {t} = useTranslation()


  const onFinish = () => {
    setFormFields(defaultFormFields);
    form.reset();
    setIsGiftCardDialogOpen(false);
  };
  const {
    mutate: postMutate,

    isPending: isPostAction,
  } = usePost({
    queryKey: "gift-cards",
    onSuccess: onFinish,
  });
  const {
    mutate: putMutate,

    isPending: isPutAction,
  } = usePut({
    queryKey: "gift-cards",
    onSuccess: onFinish,
  });

  useEffect(() => {
    if (
      formFields.code &&
    
      formFields.amount_iqd
    ) {
      setIsSubmit(true);
    } else {
      setIsSubmit(false);
    }
  }, [formFields,]);

  useEffect(() => {
    if (selectedGiftCard?.id && isGiftCardDialogOpen) {
      setFormFields({
        code: selectedGiftCard.code,
        amount_iqd: selectedGiftCard.amount_iqd,

        redeemed_at: selectedGiftCard.redeemed_at,
       
      });

      form.setValue("code", selectedGiftCard?.code);
      form.setValue("amount_iqd", selectedGiftCard?.amount_iqd);

      form.setValue("redeemed_at", selectedGiftCard?.redeemed_at);
    
    } else {
      // this is server error or other error that could happen
      setFormFields(defaultFormFields);

      form.reset();
    }
  }, [selectedGiftCard]);



  const AutoGeneratedCode = () => {
        const code=generateFormattedCode()
        setFormFields({
          ...formFields,
        code: code,
       
       
      });
      form.setValue("code", code);
  };


  const onClose = () => {
    setIsGiftCardDialogOpen(false);
    form.reset();
    setFormFields(defaultFormFields);
  };

  useEffect(() => {
    return () => {
      onClose();
    };
  }, []);

  const onSubmit = async () => {
    // Validate currency Change
    if (
      !formFields.code ||
      !formFields.amount_iqd 
 
    ) {
      return toast("Please fill all the fields");
    }

    const formData = {
      code: formFields.code,
      amount_iqd: formFields.amount_iqd,
      // redeemed_at: customFormatDate(formFields.redeemed_at),
    };
    

    if (selectedGiftCard?.id) {

      putMutate({
        endpoint: ADMIN_GIFT_CARDS_URL,
        id: selectedGiftCard?.id,

        body: formData,
      
      });
    } else {
      postMutate({
        endpoint: ADMIN_GIFT_CARDS_URL,
        body: formData,
       
      });
    }
  };

  return (
    <Dialog open={isGiftCardDialogOpen} onOpenChange={setIsGiftCardDialogOpen}>
      <DialogContent className="max-w-[95%] sm:max-w-[80%] md:w-[600px] max-h-[90vh] ">
        <ScrollArea className=" h-[300px] pr-4 w-full ">
          <DialogHeader className={"mb-4 rtl:items-end"}>
            <DialogTitle>
              {selectedGiftCard?.id ? t("Edit") : t("Create")} {t("gift card")}
            </DialogTitle>
            <DialogDescription>
              {selectedGiftCard?.id ? t("Make changes to your") : t("Create")}{" "}
              {t("gift card here. Click save when you are done.")}
            </DialogDescription>
          </DialogHeader>

          <Form {...form} className="h-full bg-black">
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 ">
              <FormField
                control={form.control}
                name="code"
                render={({ field }) => (
                  <FormItem className="w-full px-1 pt-0">
                    <FormLabel>
                      {" "}
                      {t("Code")}
                      <span className="text-red-500 text-lg">*</span>
                    </FormLabel>
                    <FormControl>
                         <div className="relative">

                      <Input
                        type="text"
                        placeholder={t("Entry card code")}
                        value={field.value}
                        onChange={(e) => {
                          field.onChange(e.target.value);

                          setFormFields({
                            ...formFields,
                            code: e.target.value,
                          });
                        }}
                        className=""
                      />
                       <Button
                              type="button"
                              variant="ghost"
                              size="icon"
                              className="absolute right-0 top-0 h-full px-3 py-1 hover:bg-transparent  hover:text-slate-900 text-slate-700 dark:text-slate-400 "
                              onClick={AutoGeneratedCode}
                            >
                       
                                <FolderCog size="16" aria-hidden="true" />
                              
                              <span className="sr-only">
                               {t("generate code")}
                              </span>
                            </Button>
                         </div>
                    </FormControl>

                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
  control={form.control}
  name="amount_iqd"
  render={({ field }) => (
    <FormItem className="w-full px-1 pt-0">
      <FormLabel>
        {" "}
        {t("Amount IQD")}
        <span className="text-red-500 text-lg">*</span>
      </FormLabel>
      <FormControl>
        <Input
          type="number"
          placeholder={t("Entry card amount")}
          value={field.value}
          onChange={(e) => {
            field.onChange(e.target.value);

            setFormFields({
              ...formFields,
              amount_iqd: e.target.value,
            });
          }}
    
          className=""
        />
      </FormControl>

      <FormMessage />
    </FormItem>
  )}
/>

                {/* <FormField
                  control={form.control}
                  name="start_date_at"
                  render={({ field }) => (
                    <FormItem className="w-full px-0 pt-0">
                      <FormLabel>
                        {" "}
                        {t("start_date_at")}
                        <span className="text-red-500 text-lg">*</span>
                      </FormLabel>
                      <FormControl>
                        <DatePicker
                          date={formFields.start_date_at}
                          setDate={(value) => {
                            field.onChange(value);

                            setFormFields({
                              ...formFields,
                              start_date_at: value,
                            });
                          }}
                        />
                      </FormControl>

                      <FormMessage />
                    </FormItem>
                  )}
                /> */}
   


              <div className="flex flex-row rtl:flex-row-reverse justify-start items-center w-full py-2 gap-4">
                <Button
                  disabled={!isSubmit || isPostAction || isPutAction}
                  type="submit"
                >
                  {isPostAction || isPutAction ? (
                    <p className="flex justify-center items-center space-x-2">
                      <Loader2 className=" h-5 w-5 animate-spin" />
                      <span>{t("Please wait")}</span>
                    </p>
                  ) : (
                    <span>{t("Save")}</span>
                  )}
                </Button>
                <Button type="button" variant="secondary" onClick={onClose}>
                  {t("Cancel")}
                </Button>
              </div>
            </form>
          </Form>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
